application: johnfiskme
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: img/apple-touch-icon.png
  upload: img/apple-touch-icon.png

- url: /favicon\.ico
  mime_type: image/png
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: \1
  upload: (robots\.txt|humans\.txt|crossdomain\.xml)

- url: /img/(.*\.(gif|png|jpg))
  static_files: img/\1
  upload: img/(.*\.(gif|png|jpg))
  
- url: /css/(.*\.css)
  mime_type: text/css
  static_files: css/\1
  upload: css/(.*\.css)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: js/\1
  upload: js/(.*\.js)

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"